### ISSUE TITLE
How do we want to approach writing CSS?

### ISSUE THREAD

**Issue by zackseuberling** [rumors-studio/programming-style-guides#1]
This seems like as good as any place to have a discussion about how we want to write our CSS in the future. I think there's no question that we're going to be using pre-compilers, so I'm not talking about that as much as how it relates to the markup.

**Comment by zackseuberling** [comment]
### Never* overwrite a base element style

Base element styles can definitely be defined somewhere in the stylesheet stack, for example all anchor tags having no underline, or something, but overwriting them deeper into the stack almost always leads to confusion and accidentally styling the wrong thing somewhere else.

**Bad**
```css
.some-section a { 
  text-decoration: underline;
}
```

**Good**
```css
.some-section a.descriptive-class { 
  text-decoration: underline;
}
```

*We can all acknowledge that never is a terrible word
