### ISSUE TITLE
Never overwrite a base element style

### ISSUE THREAD

**Issue by zackseuberling** [rumors-studio/programming-style-guides#2]
Base element styles can definitely be defined somewhere in the stylesheet stack, for example all anchor tags having no underline, or something, but overwriting them deeper into the stack almost always leads to confusion and accidentally styling the wrong thing somewhere else.

**Bad**
```css
.some-section a { 
  text-decoration: underline;
}
```

**Good**
```css
.some-section a.descriptive-class { 
  text-decoration: underline;
}
```

*We can all acknowledge that never is a terrible word
